CREATE TABLE IF NOT EXISTS admins(
    admin_id INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL, 
    username VARCHAR(100) NOT NULL,
    hash VARCHAR(150) NOT NULL, 
    reset_token TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE INDEX admin_idx ON admins(admin_id);