name: Lint, Test, Secure

on:
    push:
        branches:
            - "feat/*"
            - "fix/*"

    pull_request:
        branches:
            - main

env:
    PYTHON-VERSION: 3.12.2

jobs:
    lint:
        runs-on: ubuntu-latest
        continue-on-error: true

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{env.PYTHON-VERSION}}

            - name: Cache pip
              uses: actions/cache@v4
              with:
                  path: ~/.cache/pip
                  key: ${{runner.os}}-pip-${{hashFiles('**/requirements.txt')}}
                  restore-keys: |
                      ${{ runner.os }}-pip-

            - name: Install dependancies
              run: |
                  python -m pip install --upgrade pip 
                  pip install flake8 
                  pip install -r requirements.txt

            - name: Check Formatting
              run: black --check .

            - name: Run Flake8
              run: |
                  flake8 .
